services:
  # Backend API
  - type: web
    name: ai-job-bot-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: DEBUG
        value: false

  # Background worker for job applications
  - type: worker
    name: ai-job-bot-worker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python main.py
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false

  # Scheduled job runner
  - type: cron
    name: ai-job-bot-scheduler
    schedule: "0 10 * * *"  # Daily at 10:00 AM UTC
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python main.py
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false 